# Generated by Django 2.2 on 2020-01-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year',
            field=models.DateField(),
        ),
    ]
