# Generated by Django 2.2 on 2020-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20200124_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
    ]
