# Generated by Django 2.2 on 2020-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20200128_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='is_favourite',
            field=models.BooleanField(default='False'),
        ),
    ]
