# Generated by Django 2.2 on 2020-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_tracks_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='image_path',
        ),
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.CharField(default='Music/images/', max_length=1000),
        ),
        migrations.AddField(
            model_name='tracks',
            name='picture',
            field=models.CharField(default='Music/images/', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.CharField(default='Music/images/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
