# Generated by Django 2.2 on 2020-02-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20200204_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
