# Generated by Django 2.2 on 2020-02-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_auto_20200226_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='picture',
        ),
    ]
