# Generated by Django 2.2 on 2020-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_remove_album_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumImage',
            field=models.FileField(default='abc.jpg', upload_to='albumImages/'),
        ),
    ]
