# Generated by Django 2.2 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_album_albumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='year',
        ),
        migrations.AlterField(
            model_name='album',
            name='albumImage',
            field=models.FileField(default='abc.jpg', upload_to='images/albumImages/'),
        ),
    ]
