# Generated by Django 2.2 on 2020-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0011_auto_20200302_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='file_path',
            field=models.FileField(upload_to='songs/tracks/'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='lyric',
            field=models.FileField(upload_to='songs/lyrics/'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='picture',
            field=models.FileField(upload_to='songs/images/'),
        ),
    ]
