# Generated by Django 2.2 on 2020-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_auto_20200304_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_lyrics', models.FileField(blank=True, null=True, upload_to='songs/lyrics/')),
                ('song_image', models.FileField(blank=True, null=True, upload_to='songs/images/')),
                ('song_file_path', models.FileField(upload_to='songs/tracks/')),
                ('is_favourite', models.BooleanField(default='False')),
            ],
        ),
    ]
